### ISSUE TITLE
E2E testing webhook with successful HMAC validation

### ISSUE THREAD

**Issue by gcatanese** [adyen-examples/adyen-testing-suite#24]
The E2E Testing Suite includes a test to verify the webhook receives the payload and returns 401 (as HMAC Validation fails).

Create a new test that can verify the HMAC signature is valid and the payload can be processed

Note: we need to identify a way to create a valid HMAC signature for running the E2E testing suite

**Comment by Kwok-he-Chu** [comment]
Closed in #39 #24
